
services:
  web:
    build:
      context: .
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - src/.env
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app/src
    command: python app.py

  db:
    image: postgres
    container_name: kata_organizations_service
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: organizations_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
