
services:
  app:
    build:
      context: .
    container_name: kata_organizations_app
    environment:

        - DB_NAME=organizations_db
        - DB_USER=postgres_user
        - DB_PASSWORD=postgres_password
        - DB_HOST=db
        - DB_PORT=5432

    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres
    container_name: kata_organizations_service
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: organizations_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
