services:
  # PostgreSQL Service
  db:
    image: postgres
    container_name: kata-organizations-service
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: organizations_db
    ports:
      - "6000:5432" #Cambiar posteriormente a 5432:5432

    #Descomentar para persistir datos.
    #volumes:
     # - postgres_data:/var/lib/postgresql/data
